### ISSUE TITLE
Exchange Extension Attributes 1 to 15 - empty

### ISSUE THREAD

**Issue by goranko73** [GruberMarkus/Set-OutlookSignatures#11]
Hi,
Extension attributes ($CURRENTUSEREXTATTR1$ to $CURRENTUSEREXTATTR15$) are empty. Is there any other requirement for that to work?
Tnx

**Comment by GruberMarkus** [comment]
Thanks for reporting this issue.

Extension attributes should work out of the box.

You have found a bug:
1. The script 'default replacement variables.ps1' refers to four arrays containing Active Directory attributes (one each for the current user, it's manager, the current mailbox, and it's manager).
2. Depending on the exact AD constellation, these attributes are populated either via the PowerShell [ADSI] accelerator or via a Directory Searcher object.
3. I don't know why, but with one of these methods, the returned property names can be accessed with case insensitive names, the other method requires case sensitivity.
4. The file 'default replacement variables.ps1' in the latest releases uses lower and upper case letters for property names. This results in AD properties shown as empty, although they have values.
  
The solution is to only use lower case property names in 'default replacement variables.ps1' for accessing the AD attribute arrays. i will also place a hint for this in the file.

I will publish a hotfix release today and close this issue afterwards.

**Comment by GruberMarkus** [comment]
Could you please test the hotfix before I release it?

1. Download the attached file
2. Rename it to 'default replacement variables.ps1'
3. Replace './config/default replacement variables.ps1' with the new file
4. Run 'Set-OutlookSignatures.ps1' and let me know if extension attributes are working.

[default replacement variables.ps1.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/7105605/default.replacement.variables.ps1.txt)

**Comment by goranko73** [comment]
> Could you please test the hotfix before I release it?
> 
> 1. Download the attached file
> 2. Rename it to 'default replacement variables.ps1'
> 3. Replace './config/default replacement variables.ps1' with the new file
> 4. Run 'Set-OutlookSignatures.ps1' and let me know if extension attributes are working.
> 
> [default replacement variables.ps1.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/7105605/default.replacement.variables.ps1.txt)

It is working now...tnx a lot

**Comment by GruberMarkus** [comment]
Thank you for reporting this bug.

I hope you find Set-OutlookSignatures a useful tool. Feel free to share your feedback with me while and after your evaluation/implementation.

**Comment by goranko73** [comment]
I really appreciate the work you are doing. Thanks once again and all thumbs up!!!

**Comment by GruberMarkus** [comment]
Fixed in pull request #12, which is part of the release version 2.1.2 (https://github.com/GruberMarkus/Set-OutlookSignatures/releases/tag/v2.1.2).
