### ISSUE TITLE
Custom Signature Template

### ISSUE THREAD

**Issue by dakolta** [GruberMarkus/Set-OutlookSignatures#42]
I have made a .htm template file and put it into a directory of Main under templates, this is how I did it under v2.5.2 and it worked just fine except for the extendedattributes issue that you solve earlier. But now when I run the new v3.2.1-beta1 script I am getting the following.

Get all signature template files and categorize them @2022-07-26T16:06:54-07:00@
  'sig-master.htm' (ini index #)

Unexpected error. Exit.
Index operation failed; the array index evaluated to null.
At C:\Users\bhagler\Desktop\Set-OutlookSignatures_v3.2.1-beta1\Set-OutlookSignatures.ps1:1236 char:17
+ ...         if ($TemplateIniSettings[$TemplateIniSettingsIndex]['<Set-Out ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArrayIndex

**Comment by GruberMarkus** [comment]
For further analysis, post the complete output of the script running in verbose mode ('-Verbose' parameter), as well as you ini file.

**Comment by dakolta** [comment]
This is my folder:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/18648939/181262299-a00ed545-2f00-4feb-a266-8e9446643571.png">
 
This is thew INI file:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/18648939/181262477-ca7682f2-e1df-46bc-9558-80112ffacb28.png">

This is the output of the script:
[script-output.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/9199602/script-output.txt)

**Comment by GruberMarkus** [comment]
You set SignatureTemplatePath to '.\templates\Main', but leave SignatureIniPath at the default value of '.\templates\Signatures DOCX\_Signatures.ini'. Set SignatureIniPath to '.\templates\Main\_Signatures.ini'.<br>
With your settings, the default ini file is used, which only contains references to DOCX templates. This means, the script can't find any matches between the (.htm) files stored in SignatureTemplatePath and the (.docx) files referenced in SignatureIniPath. This, in turn, leads to the error you reported. I wrote a fix in v3.2.1-beta2, which works fine when emulation your situation in my test environment. Please test this version and let me know the result.<br>
<br>
You seem to change parameters directly in the script file, instead of passing them as script parameters (such as you did with the '-verbose' parameter). This is totally fine from a technical point of view, but makes version changes harder for you and support harder for both of us. I strongly recommend passing parameters to Set-OutlookSignatures instead of altering them directly in the script file.<br>
<br>
Do you have Outlook installed on your test machine? What Outlook version are you using? Either there is a mismatch between registry and the file system, or something is wrong in the version detection. Send me the output of this PowerShell script for verification:
```
try {
    $OutlookFileVersion = [System.Version]::Parse((((((Get-ChildItem (Get-ItemProperty "Registry::HKEY_CLASSES_ROOT\WOW6432NODE\CLSID\$((Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Outlook.Application\CLSID' -ErrorAction SilentlyContinue).'(default)')\LocalServer32" -ErrorAction SilentlyContinue).'(default)').versioninfo.fileversion + '.0.0.0.0')) -replace '^\.', '' -split '\.')[0..3] -join '.'))
} catch {
    try {
        $OutlookFileVersion = [System.Version]::Parse((((((Get-ChildItem (Get-ItemProperty "Registry::HKEY_CLASSES_ROOT\CLSID\$((Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Outlook.Application\CLSID' -ErrorAction SilentlyContinue).'(default)')\LocalServer32" -ErrorAction SilentlyContinue).'(default)').versioninfo.fileversion + '.0.0.0.0')) -replace '^\.', '' -split '\.')[0..3] -join '.'))
    } catch {
        $OutlookFileVersion = $null
    }
}
$OutlookRegistryVersion = [System.Version]::Parse(((((((Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Outlook.Application\CurVer' -ErrorAction SilentlyContinue).'(default)' -ireplace 'Outlook.Application.', '') + '.0.0.0.0')) -replace '^\.', '' -split '\.')[0..3] -join '.'))

write-host "Outlook file version: $($OutlookFileVersion)"
write-host "Outlook registry version: $($OutlookRegistryVersion)" 
```

**Comment by dakolta** [comment]
Here is the output from the ps script to get the Outlook version:
PS C:\Users\bhagler> C:\Users\bhagler\Documents\Untitled1.ps1
Outlook file version: 0.0.0.0
Outlook registry version: 16.0.0.0

But I have a new error:
Get all signature template files and categorize them @2022-07-27T08:43:08-07:00@

Unexpected error. Exit.
Cannot index into a null array.
At C:\Users\bhagler\Desktop\Set-OutlookSignatures_v3.2.1-beta2\Set-OutlookSignatures.ps1:1215 char:28
+ ...  switch ((@($TemplateIniSettings[($TemplateIniSettings.GetEnumerator( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

[script-output.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/9200655/script-output.txt)

**Comment by GruberMarkus** [comment]
That error is a real head-scratcher. It has to do with the way PowerShell treats arrays containing only one element in certain cases.

Rund this development version and post the verbose script output: [Set-OutlookSignatures.ps1.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/9202748/Set-OutlookSignatures.ps1.txt)<br>
<br>
<br>
Your Outlook installation is very interesting. Whats the registry value of "HKEY_CLASSES_ROOT\Outlook.Application\CLSID\(Default)"?

**Comment by dakolta** [comment]
Here is the output from the script you gave me:
[script-output.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/9203392/script-output.txt)
Here are the Registry entries for Outlook:
[HKEY_CLASSES_ROOT\Outlook.Application]
@="Microsoft Outlook Application"

[HKEY_CLASSES_ROOT\Outlook.Application\CLSID]
@="{0006F03A-0000-0000-C000-000000000046}"

[HKEY_CLASSES_ROOT\Outlook.Application\CurVer]
@="Outlook.Application.16"

And:
[HKEY_CLASSES_ROOT\Outlook.Application.16]
@="Microsoft Outlook 16.0 Object Library"

[HKEY_CLASSES_ROOT\Outlook.Application.16\CLSID]
@="{0006F03A-0000-0000-C000-000000000046}"

**Comment by dakolta** [comment]
Ok, I cleared out the credentials and started with a fresh download of v3.2.1-beta1, replaced thSet-OutlookSignatures.ps1 file with the Beta2 and made the change of the template folder and ini folder put in my replacement values (I understand that is not the way to do it, will fix that later).
I ran the script and everything worked, I am giving you a verbose output file:
[script-output.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/9204029/script-output.txt)

**Comment by GruberMarkus** [comment]
Good. Now let's find out what's going on with the detectin of the Outlook file version.

It could be a problem of the Office installation (registry, file system), or a problem in the script. The following PowerShell code will bring us near the reason:
```
write-host "Get Outlook file version"

try {
    write-host "  CLSID: $((Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Outlook.Application\CLSID').'(default)')"
    write-host "  WOW6432NODE"
    $OutlookFileVersion = [System.Version]::Parse((((((Get-ChildItem (Get-ItemProperty "Registry::HKEY_CLASSES_ROOT\WOW6432NODE\CLSID\$((Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Outlook.Application\CLSID' -ErrorAction Stop).'(default)')\LocalServer32" -ErrorAction Stop).'(default)' -ErrorAction Stop).versioninfo.fileversion + '.0.0.0.0')) -replace '^\.', '' -split '\.')[0..3] -join '.'))
} catch {
    write-host "    failed: $_"
    try {
        write-host "  Regular node"
        $OutlookFileVersion = [System.Version]::Parse((((((Get-ChildItem (Get-ItemProperty "Registry::HKEY_CLASSES_ROOT\CLSID\$((Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Outlook.Application\CLSID' -ErrorAction Stop).'(default)')\LocalServer32" -ErrorAction Stop).'(default)' -ErrorAction Stop).versioninfo.fileversion + '.0.0.0.0')) -replace '^\.', '' -split '\.')[0..3] -join '.'))
    } catch {
        write-host "    Failed: $_"
        $OutlookFileVersion = $null
    }
}

write-host "  $($OutlookFileVersion)"
```

**Comment by dakolta** [comment]
The version of Outlook I am using is from Office365:

  CLSID: {0006F03A-0000-0000-C000-000000000046}
  WOW6432NODE
    failed: Cannot find path 'HKEY_CLASSES_ROOT\WOW6432NODE\CLSID\{0006F03A-0000-0000-C000-000000000046}\LocalServer32' because it does not exist.
  Regular node
  16.0.15330.20264

**Comment by GruberMarkus** [comment]
Set-OutlookSignatures can now handly ini files with only one section. The Outlook file version query has been fixed, too. Closing this issue.
