### ISSUE TITLE
Missing State/Province

### ISSUE THREAD

**Issue by dakolta** [GruberMarkus/Set-OutlookSignatures#44]
I just noticed that you are missing state in the GraphUserAttributeMapping and also in the default replacement variables.

**Comment by GruberMarkus** [comment]
Added state to GraphUserAttributeMapping, default replacement variables and sample template in https://github.com/GruberMarkus/Set-OutlookSignatures/commit/dab63bc32da2121f8d06c27138183ac1f59f721d.

This fix is included in [v3.2.1-beta3](https://github.com/GruberMarkus/Set-OutlookSignatures/releases/tag/v3.2.1-beta2.).

If you want to add more properties, let me know. I will include them in default replacement variables when I see demand for many users. If you want to do it on your own, have a look at the instructions in '.\config\default replacement variables.ps1' and '.\config\default graph config.ps1'.

Please let me know if this issuse can be closed. Please also let me know the timeline of your test phase, if possible - if you can complete your tests within the next few day, I can maybe align the release of v3.2.1 with your timeline.
