### ISSUE TITLE
GraphGetUserTransitiveMemberOf is not paging aware

### ISSUE THREAD

**Issue by bieberium** [GruberMarkus/Set-OutlookSignatures#69]
Hi, thanks for your effort on this tool!

We are using your tool and came across an isse with the GraphOnly option: If a user has enough groups so that the API response is paged, only the initial batch is fetched. This can be fixed by adding a while loop like this into the function

` `
`        $InvokeRestMethod = Invoke-RestMethod @requestBody`
`       $x = $InvokeRestMethod.value`
` `
`        while ($null -ne $($InvokeRestMethod."@odata.nextLink")) {`
`            $requestBody = @{`
`                Method      = 'Get' `
`                Uri         = $($InvokeRestMethod."@odata.nextLink") `
`                Headers     = $script:authorizationHeader `
`                ContentType = 'Application/Json; charset=utf-8' `
`            } `
`            $InvokeRestMethod = Invoke-RestMethod @requestBody `
`            #$x.count `
`            $x += $InvokeRestMethod.value `
`        } `

`

**Comment by GruberMarkus** [comment]
Hi @bieberium,

thank you for bringing up this issue.

The problem has already been identified and solved. The solution will be part of release v4.0.0.
