### ISSUE TITLE
dash is not a valid dash in example script

### ISSUE THREAD

**Issue by donohueb** [GruberMarkus/Set-OutlookSignatures#81]
In the example script, the first dash or minus sign seems to be an invalid character. The dash just before "WindowsStyle". Gives an error as in the error6 pic.
![error5](https://github.com/GruberMarkus/Set-OutlookSignatures/assets/48036893/0c6a1a63-2b38-41eb-a721-2f5ba5fba79a)
![error6](https://github.com/GruberMarkus/Set-OutlookSignatures/assets/48036893/4109bac4-3de2-4835-8400-e62fd96ad902)

**Comment by GruberMarkus** [comment]
Thank you for reporting this issue!

The next release of Set-OutlookSignatures will have a correct file, without this Unicode/UTF copy-paste-error.

Please let me know if I can close this issue.

**Comment by donohueb** [comment]
Close is ok.
Thanks


Ben Donohue
IT Manager
