### ISSUE TITLE
Outlook Signatures not working in OWA

### ISSUE THREAD

**Issue by halatovic** [GruberMarkus/Set-OutlookSignatures#86]
Hello Markus,

we have implemented Set-OutlookSignatures script in organisation and it works fine for Outlook users. However, after running script with SetCurrentUserOutlookWebSignature parameter set to true only Outlook signature is generated while OWA signature is not. We have tried it on multiple users and Windows 10/11 computers.

Best Regards

Haris Alatovic

**Comment by GruberMarkus** [comment]
Please attach the full log of the script output in text format, and use the '-verbose' parameter to run the script.

**Comment by halatovic** [comment]
[Start script @2023-08-28T141809+020.txt](https://github.com/GruberMarkus/Set-OutlookSignatures/files/12454412/Start.script.%402023-08-28T141809%2B020.txt)

Hello Markus,

I have attached log file. I have removed Graph and EXO token values as well as some personal user information stored in replacement hashes.

Best Regards

Haris Alatovic

**Comment by GruberMarkus** [comment]
Do I see correctly that user with the UPN halatovic@alten-consulting.de has the primary SMTP address haris.alatovic@alten-consulting.de?

Set-OutlookSignatures can handle differing UPN and primary SMTP address beginning with version 4.0.0.

**Comment by halatovic** [comment]
Hello Markus,

yes, there is a difference among UPN and primary SMTP address for the user and users as well. Then we should move to latest version v.4.2.1 of Set-OutlookSignatures. We have customized some replacement hashes and HTML template file. I guess we could used customized files with Set-OutlookSignatures version 4.2.1?

**Comment by GruberMarkus** [comment]
Hi Haris,

yes, you can use customized replacement hashes and HTML templates files with v4.2.1, too.

Please make sure you go through the changelog to see if you have to adop anything else before you switch to a new version (Set-OutlookSignatures follows semantic versioning, so there are breaking changes from v3 to v4).

As soon as the free and open-source version of v4 works fine, i recommend to request a trial version of v4 from https://explicitconsulting.at/.

The v4 release will also help you with multiple signatures in the cloud, as there is an experimental feature built in for exactly this use-case.

**Comment by GruberMarkus** [comment]
I close this request as the issue (user UPN and primary SMTP address differ) can not be solved in v3.6.1, and is resolved in v4.

If the problem is not solved in v4, please re-open this issue or create a new one.

**Comment by halatovic** [comment]
Hello Markus,

thank you for your support. Issue may be closed.

Best Regards

Haris Alatovic
